clickhouse:
  hosts:
    localhost:
      ansible_connection: local
      ansible_become: yes

vector:
  hosts:
    localhost:
      ansible_connection: local
      ansible_host: 127.0.0.1

lighthouse:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      ansible_connection: local
